function MaskDepress(content) {
    this.content = content;
    this.GetMaskD = function () {
        $(this.content).empty().append($("<table class='table table-border table-hover' frame='below' width='100%'><thead><tr align='center'><th width='60%'>ในช่วง 2 สัปดาห์ที่ผ่านมารวมทั้งวันนี้<p>ท่านมีอาการเหล่านี้ บ่อยแค่ไหน</th><td width='10%' valign='top'><b>ไม่มีเลย</b></td><th width='10%'>บางวัน<p>1-7วัน</th><th width='10%'>บ่อย<p> >7วัน</th><td width='10%'  valign='top'><b>ทุกวัน</b></td></tr></thead><tbody id='A2'></tbody></table>"));
            
    $("tbody#A2").append($("<tr><td>1. คิดทำร้ายตัวเอง หรือคิดว่าถ้าตายไปคงจะดี</td><td align='center'><input type='radio' name='9Q-9' value='0' checked required></td><td align='center'><input type='radio' name='9Q-9' value='1' required></td><td align='center'><input type='radio' name='9Q-9' value='2' required></td><td align='center'><input type='radio' name='9Q-9' value='3' required></td></tr>")
            , $("<tr><td>2. เบื่อ ไม่สนใจอยากทำอะไร</td><td align='center'><input type='radio' name='9Q-1' value='0' checked required></td><td align='center'><input type='radio' name='9Q-1' value='1' required></td><td align='center'><input type='radio' name='9Q-1' value='2' required></td><td align='center'><input type='radio' name='9Q-1' value='3' required></td></tr>")
            , $("<tr><td>3. เบื่ออาหารหรือกินมากเกินไป</td><td align='center'><input type='radio' name='9Q-5' value='0' checked required></td><td align='center'><input type='radio' name='9Q-5' value='1' required></td><td align='center'><input type='radio' name='9Q-5' value='2' required></td><td align='center'><input type='radio' name='9Q-5' value='3' required></td></tr>")
            , $("<tr><td>4. พูดช้า ทำอะไรช้าลงจนคนอื่นสังเกตุเห็นได้ หรือกระสับกระส่ายไม่สามารถอยู่นิ่งได้เหมือนที่เคยเป็น</td><td align='center'><input type='radio' name='9Q-8' value='0' checked required></td><td align='center'><input type='radio' name='9Q-8' value='1' required></td><td align='center'><input type='radio' name='9Q-8' value='2' required></td><td align='center'><input type='radio' name='9Q-8' value='3' required></td></tr>")
            , $("<tr><td>5. ไม่สบายใจ ซึมเศร้า ท้อแท้</td><td align='center'><input type='radio' name='9Q-2' value='0' checked required></td><td align='center'><input type='radio' name='9Q-2' value='1' required></td><td align='center'><input type='radio' name='9Q-2' value='2' required></td><td align='center'><input type='radio' name='9Q-2' value='3' required></td></tr>")
            , $("<tr><td>6. รู้สึกไม่ดีกับตัวเอง คิดว่าตัวเองล้มเหลวหรือครอบครัวผิดหวัง</td><td align='center'><input type='radio' name='9Q-6' value='0' checked required></td><td align='center'><input type='radio' name='9Q-6' value='1' required></td><td align='center'><input type='radio' name='9Q-6' value='2' required></td><td align='center'><input type='radio' name='9Q-6' value='3' required></td></tr>")
            , $("<tr><td>7. สมาธิไม่ดี เวลาทำอะไร เช่น ดูโทรทัศน์ ฟังวิทยุ หรือทำงานที่ต้องใช้ความตั้งใจ</td><td align='center'><input type='radio' name='9Q-7' value='0' checked required></td><td align='center'><input type='radio' name='9Q-7' value='1' required></td><td align='center'><input type='radio' name='9Q-7' value='2' required></td><td align='center'><input type='radio' name='9Q-7' value='3' required></td></tr>")
            , $("<tr><td>8. หลับยากหรือหลับๆตื่นๆหรือหลับมากไป</td><td align='center'><input type='radio' name='9Q-3' value='0' checked required></td><td align='center'><input type='radio' name='9Q-3' value='1' required></td><td align='center'><input type='radio' name='9Q-3' value='2' required></td><td align='center'><input type='radio' name='9Q-3' value='3' required></td></tr>")
            , $("<tr><td>9. เหนื่อยง่ายหรือไม่ค่อยมีแรง</td><td align='center'><input type='radio' name='9Q-4' value='0' checked required></td><td align='center'><input type='radio' name='9Q-4' value='1' required></td><td align='center'><input type='radio' name='9Q-4' value='2' required></td><td align='center'><input type='radio' name='9Q-4' value='3' required></td></tr>")
            , $("<tr><td colspan='3' align='right'><b id='res-9Q'></b></td><td colspan='2' align='right'><a class='btn btn-success' id='process9Q'>ประมวลผล 9Q</a><td></tr>"));

    }

}
